### ISSUE TITLE
MLP error

### ISSUE THREAD

**Issue by SyedTauhidUllahShah** [enningxie/Neural-Collaborative-Filtering#1]
It is giving me this error InvalidArgumentError: indices[28,0] = 12928 is not in [0, 12926)
	 [[{{node item_embedding_3/embedding_lookup}}]].

**Comment by enningxie** [comment]
> It is giving me this error InvalidArgumentError: indices[28,0] = 12928 is not in [0, 12926)
> [[{{node item_embedding_3/embedding_lookup}}]].

It may be helpful to rescale the input features before the embedding layer.

**Comment by SyedTauhidUllahShah** [comment]
> > It is giving me this error InvalidArgumentError: indices[28,0] = 12928 is not in [0, 12926)
> > [[{{node item_embedding_3/embedding_lookup}}]].
> 
> It may be helpful to rescale the input features before the embedding layer.

I'm a newbie in this area. I would really appreciate if you can please tell me about the exact code to get rid from the error.

**Comment by enningxie** [comment]
> > > It is giving me this error InvalidArgumentError: indices[28,0] = 12928 is not in [0, 12926)
> > > [[{{node item_embedding_3/embedding_lookup}}]].
> > 
> > 
> > It may be helpful to rescale the input features before the embedding layer.
> 
> I'm a newbie in this area. I would really appreciate if you can please tell me about the exact code to get rid from the error.

Just reindex the `user_id ` to `[0, num_users) ` and the `item_id ` to `[0, num_items)` before  `get_train_instances()` function, good luck.

**Comment by SyedTauhidUllahShah** [comment]
> item_id

what does u mean by user_id and item_id? There's nothing like that inside the program.

**Comment by enningxie** [comment]
yeah.
